server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:devdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

# PostgreSQL configuration (commented out - uncomment to use PostgreSQL)
#  datasource:
#    url: jdbc:postgresql://localhost:5432/order_sourcing
#    username: demouser
#    password: 123456
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true