server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_sourcing_test
    driverClassName: org.postgresql.Driver
    username: demouser
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data-test.sql